name: Dummy Workflow

on:
  pull_request_review:
    types:
      - submitted

jobs:
  test-job:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Greeting
        run: echo "Hello, World! This is a test of the dummy workflow."