name: Build and Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Prepare Template for S3 Deployment
        run: |
          TEMPLATE_FILE='lambda-template.yaml'
          S3_BUCKET_KEY='new-relic-log-forwarder-folder/new-relic-log-forwarder.zip'
          
          # Replace CodeUri from local path to S3 structure
          sed -i "s|CodeUri: /src|CodeUri:\n    Bucket: !FindInMap [ RegionToS3Bucket, !Ref 'AWS::Region', BucketArn ]\n    Key: '${S3_BUCKET_KEY}'|" "$TEMPLATE_FILE"
          
          echo "Template file updated successfully with S3 bucket as CodeUri."

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_SAR_PUBLISHER_ROLE }}
          aws-region: us-east-2

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM Application
        run: sam build --template-file template.yaml --region us-east-2

      - name: Package SAM Application
        run: sam package --s3-bucket unified-lambda-cft-1 --output-template-file packaged.yaml --region us-east-2
# should we include retries as part of uploading?
      - name: Upload CloudFormation Template to S3
        run: aws s3 cp packaged.yaml s3://unified-lambda-serverless-1/packaged.yaml
